<?php

/**
 * Implements hook_page_alter().
 */
function ipe_page_alter(&$page) {
  if (isset($page['page_top']['toolbar'])) {
    // Remove the toolbar drawer toggle by overriding toolbar.module's pre-render
    // function with our own.
    if (isset($page['page_top']['toolbar']['#pre_render'][0]) && $page['page_top']['toolbar']['#pre_render'][0] == 'toolbar_pre_render') {
      $page['page_top']['toolbar']['#pre_render'][0] = 'ipe_override_toolbar_pre_render';
    }
    // Replace the shortcut.module's toolbar pre-render function with our own.
    if (isset($page['page_top']['toolbar']['#pre_render'][1]) && $page['page_top']['toolbar']['#pre_render'][1] == 'shortcut_toolbar_pre_render') {
      $page['page_top']['toolbar']['#pre_render'][1] = 'ipe_override_shortcut_toolbar_pre_render';
    }

    // If the toolbar is available, add a pre-render function to display the
    // view/edit mode toggle.
    $page['page_top']['toolbar']['#pre_render'][] = 'ipe_toolbar_pre_render';
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function ipe_module_implements_alter(&$implementations, $hook) {
  // Run ipe's hook_page_alter() after shortcut's, but retain the ordering.
  // We need this to be able to override shortcut's #pre_render callback for
  // rendering the shortcuts into the toolbar.
  if ($hook == 'page_alter') {
    unset($implementations['ipe']);
    $index = array_search('shortcut', array_keys($implementations));
    $implementations = array_slice($implementations, 0, $index + 1) + array('ipe' => FALSE) + array_slice($implementations, $index + 1);
  }
}

/**
 * Implements of hook_preprocess_HOOK().
 */
function ipe_preprocess_page(&$var) {
  // Special case: on node pages, the title of the node becomes the page title.
  if (array_key_exists('node', $var) && entity_access('update', 'node', $var['node'])) {
    // Pseudofield: title.
    $node_type = node_type_get_type($var['node']->type);
    if ($node_type->has_title) {
      $attributes = array(
        'class' => 'ipe-pseudofield ipe-field ipe-allowed',
        'data-ipe-field-label' => $node_type->title_label,
      );
      $var['title_prefix']['ipe']['#markup'] = '<div ' . drupal_attributes($attributes) . '">';
      $var['title_suffix']['ipe']['#markup'] = '</div>';
    }
  }
}

/**
 * Implements of hook_preprocess_HOOK().
 */
function ipe_preprocess_node(&$var) {
  $entity_type = $var['elements']['#entity_type'];
  $entity      = $var['elements']['#node'];

  if (entity_access('update', $entity_type, $entity)) {
    list($id, $vid, $bundle) = entity_extract_ids($entity_type, $entity);
    $i = entity_get_info($entity_type);

    // Provide metadata through data-* attributes.
    $data_attributes = array(
      'data-ipe-entity-label'    => $i['bundles'][$bundle]['label'],
      'data-ipe-entity-edit-url' => url("node/$id/edit"),
    );
    $var['attributes_array'] += $data_attributes;

    // Mark this entity as editable.
    $var['classes_array'][] = 'ipe-entity ipe-allowed';


    // Pseudofield: title.
    $node_type = node_type_get_type($bundle);
    if ($node_type->has_title) {
      $var['title_attributes_array']['class'] = 'ipe-pseudofield ipe-field ipe-allowed';
      $var['title_attributes_array']['data-ipe-field-label'] = $node_type->title_label;
    }
  }
}

/**
 * Implements of hook_preprocess_HOOK().
 */
function ipe_preprocess_field(&$var) {
  $entity_type = $var['element']['#entity_type'];
  $entity      = $var['element']['#object'];
  $field_name  = $var['element']['#field_name'];

  // For now, we only support editing of nodes in the full view mode.
  // TODO: investigate how to offer IPE in other view modes. Also: full view mode does not necessarily imply
  // that content does not get shortened etc. We should consider each field individually.
  $view_mode   = $var['element']['#view_mode'];
  if ($view_mode != 'full') {
    return;
  }

  if (entity_access('update', $entity_type, $entity) && field_access('edit', $field_name, $entity_type, $entity)) {
    list($id, $vid, $bundle) = entity_extract_ids($entity_type, $entity);
    $ei = entity_get_info($entity_type);
    $fi = field_info_instance($entity_type, $field_name, $bundle);

    // Provide metadata through data-* attributes.
    $data_attributes = array(
      'data-ipe-field-label' => $fi['label'],
    );
    if (!array_key_exists('attributes_array', $var)) {
      $var['attributes_array'] = array();
    }
    $var['attributes_array'] += $data_attributes;

    // Mark this field as editable.
    $var['classes_array'][] = 'ipe-field ipe-allowed';
  }
}

/**
 * Pre-render function for ipe.module; view/edit mode toggle.
*/
function ipe_toolbar_pre_render($toolbar) {
  $module_path = drupal_get_path('module', 'ipe');
require_once 'includes/form.inc';
  $toolbar['toolbar_drawer'][] = array(
    'view_edit_toggle' => array(
      // TODO: make this less hacky; but we might move to something else than radios!
      '#markup' => '
<div id="ipe-view-edit-toggle" class="form-radios">
  <div class="form-item form-type-radio">
    <input type="radio" id="ipe-view-edit-toggle--view" value="view" class="form-radio" name="ipe_view_edit_toggle" checked="checked">
    <label class="option" for="ipe-view-edit-toggle--view">' . t('View') . '</label>
  </div>
  <div class="form-item form-type-radio">
    <input type="radio" id="ipe-view-edit-toggle--edit" value="edit" class="form-radio" name="ipe_view_edit_toggle">
    <label class="option" for="ipe-view-edit-toggle--edit">' . t('Edit') . '</label>
  </div>
</div>',
      '#attached' => array(
        'js' => array(
          $module_path . '/js/ipe.js',
        ),
        'css' => array(
          $module_path . '/css/ipe.css',
        ),
      ),
    ),
  );

  return $toolbar;
}

/**
 * Override of pre-render function for toolbar.module.
 */
function ipe_override_toolbar_pre_render($toolbar) {
  // The original.
  $toolbar = toolbar_pre_render($toolbar);

  // The toolbar should never be collapsed.
  $_COOKIE['Drupal_toolbar_collapsed'] = 0;

  // Now we remove the toolbar drawer toggle.
  unset($toolbar['toolbar_toggle']);

  $toolbar['#attached']['css'][] = drupal_get_path('module', 'ipe') . '/overrides.css';

  return $toolbar;
}

/**
 * Override of pre-render function for shortcut.module.
 */
function ipe_override_shortcut_toolbar_pre_render($toolbar) {
  // The original.
  $toolbar = shortcut_toolbar_pre_render($toolbar);

  // Put the shortcuts themselves *after* their configure link in the HTML,
  // because we'll float them right.
  $shortcuts = array_shift($toolbar['toolbar_drawer'][0]);
  array_push($toolbar['toolbar_drawer'][0], $shortcuts);

  $toolbar['#attached']['css'][] = drupal_get_path('module', 'ipe') . '/overrides.css';

  return $toolbar;
}

